Ready for Review
Morrism1/Enumerables pull request #2
Opened 2020-05-09 19:07 UTC by Morrism1

## Enumerable Methods
I created the following enumerables 👍 :
- #each
- #each_with_index
- #select
- #all?
- #any?
- #none?
- #count
- #inject
- #map
and a Method to test **my_inject** called Multiply_els

Today there is no live version 👎, Thanks for Review 💯

2020-05-10 22:45 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @Morrism1 

Well job done so far. However, there are some changes you should.
Please, read the comments left below.

Kindly make the changes and submit a new code review request.
Thanks

Mael FOSSO

2020-05-10 22:45 UTC, maelfosso commented on enumerable.rb
> +  end
```ruby
2.6.5 :007 > array
 => [4, 0, 6, 3, 5, 7, 1, 6, 5, 1, 6, 0, 6, 0, 4, 2, 5, 0, 0, 4, 0, 0, 3, 0, 6, 0, 4, 7, 3, 0, 3, 7, 4, 8, 5, 7, 1, 8, 5, 7, 0, 5, 3, 4, 3, 2, 6, 5, 5, 2, 0, 4, 1, 1, 8, 6, 4, 6, 0, 3, 2, 5, 7, 5, 6, 6, 7, 4, 2, 8, 3, 1, 4, 5, 8, 3, 6, 6, 8, 4, 4, 3, 8, 6, 4, 8, 8, 8, 2, 0, 5, 0, 4, 6, 6, 6, 2, 0, 0, 6] 
2.6.5 :008 > true_block = proc { |num| num > 9 }
 => #<Proc:0x000055d176a526f0@(irb):8> 
2.6.5 :009 > array.none?(&true_block)
 => true 
2.6.5 :010 > array.my_none?(&true_block)
 => false 
2.6.5 :011 > 
```

2020-05-10 22:45 UTC, maelfosso commented on enumerable.rb
> +  end
```ruby
2.6.5 :013 > array
 => [4, 0, 6, 3, 5, 7, 1, 6, 5, 1, 6, 0, 6, 0, 4, 2, 5, 0, 0, 4, 0, 0, 3, 0, 6, 0, 4, 7, 3, 0, 3, 7, 4, 8, 5, 7, 1, 8, 5, 7, 0, 5, 3, 4, 3, 2, 6, 5, 5, 2, 0, 4, 1, 1, 8, 6, 4, 6, 0, 3, 2, 5, 7, 5, 6, 6, 7, 4, 2, 8, 3, 1, 4, 5, 8, 3, 6, 6, 8, 4, 4, 3, 8, 6, 4, 8, 8, 8, 2, 0, 5, 0, 4, 6, 6, 6, 2, 0, 0, 6] 
2.6.5 :014 > array.none?(String)
 => true 
2.6.5 :015 > array.my_none?(String)
Traceback (most recent call last):
        5: from /home/maelfosso/.rvm/rubies/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/rubies/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        2: from (irb):15
        1: from enumerable.rb:64:in `my_none?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :016 > 
```

2020-05-10 22:45 UTC, maelfosso commented on enumerable.rb
> +  end
```ruby
2.6.5 :018 > words = %w[dog door rod blade]
 => ["dog", "door", "rod", "blade"] 
2.6.5 :019 > words.none?(/z/)
 => true 
2.6.5 :020 > words.my_none?(/z/)
Traceback (most recent call last):
        5: from /home/maelfosso/.rvm/rubies/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/rubies/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        2: from (irb):20
        1: from enumerable.rb:64:in `my_none?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :021 > 
```

2020-05-10 22:45 UTC, maelfosso commented on enumerable.rb
> +  end
```ruby
2.6.5 :022 > words
 => ["dog", "door", "rod", "blade"] 
2.6.5 :023 > words.none?(5)
 => true 
2.6.5 :024 > words.my_none?(5)
Traceback (most recent call last):
        5: from /home/maelfosso/.rvm/rubies/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/rubies/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        2: from (irb):24
        1: from enumerable.rb:64:in `my_none?'
ArgumentError (wrong number of arguments (given 1, expected 0))
2.6.5 :025 > 
```

2020-05-10 22:45 UTC, maelfosso commented on enumerable.rb
> +end
```ruby
2.6.5 :027 > range = Range.new(5, 50)
 => 5..50 
2.6.5 :028 > range.inject(4) { |prod, n| prod * n }
 => 5069015533618896340602101361010794807396273594826752000000000000 
2.6.5 :029 > range.my_inject(4) { |prod, n| prod * n }
Traceback (most recent call last):
        6: from /home/maelfosso/.rvm/rubies/ruby-2.6.5/bin/irb:23:in `<main>'
        5: from /home/maelfosso/.rvm/rubies/ruby-2.6.5/bin/irb:23:in `load'
        4: from /home/maelfosso/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        3: from (irb):29
        2: from enumerable.rb:95:in `my_inject'
        1: from enumerable.rb:7:in `my_each'
NoMethodError (undefined method `[]' for 5..50:Range)
2.6.5 :030 > 
```

2020-05-10 22:45 UTC, maelfosso commented on enumerable.rb
> +end
```ruby
2.6.5 :032 > array
 => [4, 0, 6, 3, 5, 7, 1, 6, 5, 1, 6, 0, 6, 0, 4, 2, 5, 0, 0, 4, 0, 0, 3, 0, 6, 0, 4, 7, 3, 0, 3, 7, 4, 8, 5, 7, 1, 8, 5, 7, 0, 5, 3, 4, 3, 2, 6, 5, 5, 2, 0, 4, 1, 1, 8, 6, 4, 6, 0, 3, 2, 5, 7, 5, 6, 6, 7, 4, 2, 8, 3, 1, 4, 5, 8, 3, 6, 6, 8, 4, 4, 3, 8, 6, 4, 8, 8, 8, 2, 0, 5, 0, 4, 6, 6, 6, 2, 0, 0, 6] 
2.6.5 :033 > array.inject(:+)
 => 397 
2.6.5 :034 > array.my_inject(:+)
 => #<Enumerator: [4, 0, 6, 3, 5, 7, 1, 6, 5, 1, 6, 0, 6, 0, 4, 2, 5, 0, 0, 4, 0, 0, 3, 0, 6, 0, 4, 7, 3, 0, 3, 7, 4, 8, 5, 7, 1, 8, 5, 7, 0, 5, 3, 4, 3, 2, 6, 5, 5, 2, 0, 4, 1, 1, 8, 6, 4, 6, 0, 3, 2, 5, 7, 5, 6, 6, 7, 4, 2, 8, 3, 1, 4, 5, 8, 3, 6, 6, 8, 4, 4, 3, 8, 6, 4, 8, 8, 8, 2, 0, 5, 0, 4, 6, 6, 6, 2, 0, 0, 6]:my_inject> 
2.6.5 :035 > 
```

2020-05-10 22:45 UTC, maelfosso commented on enumerable.rb
> +  end
That method is blocking. 
Please, find why.

2020-05-12 16:19 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @Morrism1 :handshake: 

### You've done a great job with this project :1st_place_medal: everything is working correctly except your my_each_with_index so let's fix it :construction: :construction_worker: 

I've left comments directly in your code with some test cases to show what's wrong with your my_each_with_index

### That's it! :raised_hands: 

### Please :pray: do the changes :technologist:  and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-05-12 16:19 UTC, euqueme commented on enumerable.rb
> +  end
* [ ] should have working `my_each_with_index` identical and returns the same thing as ruby's [`each_with_index`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-each_with_index). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each_with_index.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

#### my_each_with_index

- [ ] my_each_with_index calls the given block once for each element in self

Given this
```ruby
block = proc { |x, i| puts x + i }
```
when executing these commands 
```ruby
[1, 5, 2].my_each_with_index(&block) 
[1, 5, 2].each_with_index(&block) 
[1, 5, 2].my_each_with_index{ |x| puts x + i }  
[1, 5, 2].each_with_index{ |x| puts x + i } 
```
should  all return the same result
```ruby
#result
1
6
4
```
- Yours is stuck on a loop only printing '1' because you never increment the item so it never breaks the while loop (I had to stop the process)
![image](https://user-images.githubusercontent.com/52209067/81701148-d9aec880-9426-11ea-9f26-2ee0704b85a3.png)

- Real each_with_index
![image](https://user-images.githubusercontent.com/52209067/77679518-41cd4c00-6f58-11ea-87ab-3164a3a5829e.png)

2020-05-13 08:28 UTC, maelfosso approved these changes
# Congratulations :clap: 

It's OK :smile: You can merge it :+1: 
Good continuation :handshake: 

Mael FOSSO

2020-05-13 15:03 UTC, merged